Traceback (most recent call last):
  File "<string>", line 9, in <module>
OSError: [Errno 38] Function not implemented
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 55, in apport_excepthook
    import apt_pkg
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
OSError: [Errno 38] Function not implemented: '/home/yashd/private/CS537_Team/cs537/p6/tests/mnt'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
OSError: [Errno 38] Function not implemented
